# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'altech_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(866, 586)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Logo/src/icon/Altech Logo.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.camWindow3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camWindow3.sizePolicy().hasHeightForWidth())
        self.camWindow3.setSizePolicy(sizePolicy)
        self.camWindow3.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.camWindow3.setStyleSheet("background-color: rgb(0, 0, 58);\n"
"font: 8pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.camWindow3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.camWindow3.setScaledContents(True)
        self.camWindow3.setAlignment(QtCore.Qt.AlignCenter)
        self.camWindow3.setObjectName("camWindow3")
        self.gridLayout_2.addWidget(self.camWindow3, 0, 2, 1, 1)
        self.camWindow2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camWindow2.sizePolicy().hasHeightForWidth())
        self.camWindow2.setSizePolicy(sizePolicy)
        self.camWindow2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.camWindow2.setStyleSheet("background-color: rgb(0, 0, 58);\n"
"font: 8pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.camWindow2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.camWindow2.setScaledContents(True)
        self.camWindow2.setAlignment(QtCore.Qt.AlignCenter)
        self.camWindow2.setObjectName("camWindow2")
        self.gridLayout_2.addWidget(self.camWindow2, 0, 1, 1, 1)
        self.camWindow1 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camWindow1.sizePolicy().hasHeightForWidth())
        self.camWindow1.setSizePolicy(sizePolicy)
        self.camWindow1.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.camWindow1.setStyleSheet("background-color: rgb(0, 0, 58);\n"
"font: 8pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.camWindow1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.camWindow1.setScaledContents(True)
        self.camWindow1.setAlignment(QtCore.Qt.AlignCenter)
        self.camWindow1.setObjectName("camWindow1")
        self.gridLayout_2.addWidget(self.camWindow1, 0, 0, 1, 1)
        self.camWindow4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camWindow4.sizePolicy().hasHeightForWidth())
        self.camWindow4.setSizePolicy(sizePolicy)
        self.camWindow4.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.camWindow4.setStyleSheet("background-color: rgb(0, 0, 58);\n"
"font: 8pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.camWindow4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.camWindow4.setScaledContents(True)
        self.camWindow4.setAlignment(QtCore.Qt.AlignCenter)
        self.camWindow4.setObjectName("camWindow4")
        self.gridLayout_2.addWidget(self.camWindow4, 0, 3, 1, 1)
        self.tabs = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabs.setFont(font)
        self.tabs.setAutoFillBackground(False)
        self.tabs.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.tabs.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabs.setObjectName("tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.txt_log = QtWidgets.QTextEdit(self.frame)
        self.txt_log.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.txt_log.setReadOnly(True)
        self.txt_log.setObjectName("txt_log")
        self.gridLayout_3.addWidget(self.txt_log, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/preview_icon/src/icon/preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.tab, icon1, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_2.setStyleSheet("font: 9pt \"Segoe UI\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 2, 0, 1, 1)
        self.btn_EraseIdentity = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_EraseIdentity.setAutoFillBackground(False)
        self.btn_EraseIdentity.setStyleSheet("background-color: rgb(75, 150, 0);\n"
"font: 13pt \"Segoe UI\";")
        self.btn_EraseIdentity.setDefault(True)
        self.btn_EraseIdentity.setFlat(True)
        self.btn_EraseIdentity.setObjectName("btn_EraseIdentity")
        self.gridLayout_5.addWidget(self.btn_EraseIdentity, 1, 0, 1, 1)
        self.btn_RegisterIdentity = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_RegisterIdentity.setAutoFillBackground(False)
        self.btn_RegisterIdentity.setStyleSheet("background-color: rgb(75, 150, 0);\n"
"font: 13pt \"Segoe UI\";")
        self.btn_RegisterIdentity.setDefault(True)
        self.btn_RegisterIdentity.setFlat(True)
        self.btn_RegisterIdentity.setObjectName("btn_RegisterIdentity")
        self.gridLayout_5.addWidget(self.btn_RegisterIdentity, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab_5)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.list_names = QtWidgets.QListView(self.frame_2)
        self.list_names.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.list_names.setFrameShadow(QtWidgets.QFrame.Plain)
        self.list_names.setObjectName("list_names")
        self.gridLayout_4.addWidget(self.list_names, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_2, 0, 1, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/database_icon/src/icon/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.tab_5, icon2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_9.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tree_cloud_directory = QtWidgets.QTreeWidget(self.frame_3)
        self.tree_cloud_directory.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.tree_cloud_directory.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tree_cloud_directory.setObjectName("tree_cloud_directory")
        self.gridLayout_7.addWidget(self.tree_cloud_directory, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_3, 0, 1, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/cloud_icon/src/icon/cloud.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.tab_3, icon3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_5 = QtWidgets.QFrame(self.tab_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tree_local_directory = QtWidgets.QTreeWidget(self.frame_5)
        self.tree_local_directory.setAutoFillBackground(False)
        self.tree_local_directory.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.tree_local_directory.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tree_local_directory.setAlternatingRowColors(False)
        self.tree_local_directory.setObjectName("tree_local_directory")
        self.gridLayout_10.addWidget(self.tree_local_directory, 1, 0, 1, 1)
        self.btn_sync = QtWidgets.QPushButton(self.frame_5)
        self.btn_sync.setAutoFillBackground(False)
        self.btn_sync.setStyleSheet("background-color: rgb(75, 150, 0);\n"
"font: 13pt \"Segoe UI\";")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/upload_icon/src/icon/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sync.setIcon(icon4)
        self.btn_sync.setDefault(True)
        self.btn_sync.setFlat(True)
        self.btn_sync.setObjectName("btn_sync")
        self.gridLayout_10.addWidget(self.btn_sync, 2, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_5, 0, 1, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/storage_icon/src/icon/storage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.tab_4, icon5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setHorizontalSpacing(30)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_14.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_14.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_14.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_14.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_14.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setStyleSheet("font: 13pt \"Segoe UI\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_14.addWidget(self.label_11, 2, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_14, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem1, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout_13.addWidget(self.label_4, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/about_icon/src/icon/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.tab_2, icon6, "")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CDS-1"))
        self.camWindow3.setText(_translate("MainWindow", "CAMERA 3"))
        self.camWindow2.setText(_translate("MainWindow", "CAMERA 2"))
        self.camWindow1.setText(_translate("MainWindow", "CAMERA 1"))
        self.camWindow4.setText(_translate("MainWindow", "CAMERA 4"))
        self.label.setText(_translate("MainWindow", "Data Logging"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("MainWindow", "Preview"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Actions"))
        self.btn_EraseIdentity.setText(_translate("MainWindow", "Erase Existing Identity"))
        self.btn_RegisterIdentity.setText(_translate("MainWindow", "Register New Identity"))
        self.label_2.setText(_translate("MainWindow", "Authorized Identities"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_5), _translate("MainWindow", "Database"))
        self.tree_cloud_directory.headerItem().setText(0, _translate("MainWindow", "Cloud Directory"))
        self.tree_cloud_directory.headerItem().setText(1, _translate("MainWindow", "Date & Time"))
        self.tree_cloud_directory.headerItem().setText(2, _translate("MainWindow", "ID"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _translate("MainWindow", "Cloud Storage"))
        self.tree_local_directory.headerItem().setText(0, _translate("MainWindow", "Local Directory"))
        self.tree_local_directory.headerItem().setText(1, _translate("MainWindow", "Date & Time"))
        self.btn_sync.setText(_translate("MainWindow", "Sync"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), _translate("MainWindow", "Local Storage"))
        self.label_9.setText(_translate("MainWindow", "Aesthetics & Ergonomics"))
        self.label_8.setText(_translate("MainWindow", "Daniela L. Espeña"))
        self.label_6.setText(_translate("MainWindow", "Eugene B. Oca"))
        self.label_7.setText(_translate("MainWindow", "Machine Learning Programmer"))
        self.label_10.setText(_translate("MainWindow", "Allen Joshua G. Calderon"))
        self.label_11.setText(_translate("MainWindow", "Circuit Design Integrator"))
        self.label_4.setText(_translate("MainWindow", "AL-TECHNOLOGIES"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("MainWindow", "About"))

import resources_rc
